### ISSUE TITLE
Great work, unfortunately, seems non-usable at this point 

### ISSUE THREAD

**Issue by lgandecki** [gadicc/meteor-blaze-virtual-dom#1]
This sounds like an amazing idea.
Did you get this to work in any real-life projects?

I put two of mine to test - one is the opensource thebrain.pro 
https://github.com/lgandecki/TheBrain

and one proprietary app that I develop at work.
And it didn't work on either :(

Looks like comments in the html are not working,
so I did 
`if (document.createComment) {
            intoArray.push(document.createComment(htmljs.sanitizedValue));
    }`

in materializer.js 

Then I got rid of iron router and it at least render something, but the styling was off. 

I'm interested to hear what's your plan for this, and if there is anything I could do to help. 

Thanks a lot!

**Comment by gadicc** [comment]
Thanks!  Yeah, it's just proof-of-concept code :>  Thanks also for the heads up re HTML comments.  Otherwise do anything in your apps (helper, events, lifecycle callback) touch the DOM directly?  But yeah it's only tested against the included demo and pretty much nothing else.

The plans are as follows:  I wrote this to solve performance issues in apps using famous-views.  I'd like to spend more time on this, and make it an officially supported famous-views pattern (thereby initially targetting users who are willing to go the extra mile for performance).  And then after it's been well tested with real usage and suggested patterns, have a more widespread release.

However, right now all my time is going to the new version of Famous.  Can't optimize performance when you can't write an app yet :)  So currently I'm not working on it... but plan to invest my time quite heavily in it moving forward.

Thanks also for your offer to help!  Perhaps subscribe/watch to the repo and then you'll get a notification when I'm working on this again?  Are you interested in helping develop the core code too or more about testing releases?  Either are appreciated :)

**Comment by lgandecki** [comment]
This might be game-changer for our app so I might be able to squeeze in some work-hours into this. I just wouldn't even know where to start at this moment.

What do you mean by "touching DOM directly"? like, doing jQuery things on them, switching classes, etc?

**Comment by s20307** [comment]
I occurrence some error from 'attrs.js'
It error message is 'Uncaught TypeError: element.getAttribute is not a function'
(I'm using Meteor version : METEOR@1.1.0.2)

Look under the code line please.

var StyleHandler = DiffingAttributeHandler.extend({
  getCurrentValue: function (element) {
    //this line
    return element.getAttribute('style');
  },
  setValue: function (element, style) {
    if (style === '') {
      element.removeAttribute('style');
    } else {
      element.setAttribute('style', style);
    }
  },

**Comment by gadicc** [comment]
In that case I'd say wait for now, I'll expect to resume work on this in the coming months as we'd ideally like to use it for our app too.

Yeah.  Changing classes via a template would be fine - class={{classes}} - or whatever, but $('#div').addClass('something'), well, where would this happen (rendered callback?) which DOM should it be using (very NB if we use web workers where code will be in different threads), etc.

**Comment by ghost** [comment]
If you guys are looking to use a Blaze syntax with a virtual dom, check out https://github.com/timbrandin/meteor-sideburns It's Blaze syntax/API and with React under the hood. It compiles into regular React templates during Meteor's build process. Probably would be much faster to help with that project than to write a vdom. Plus all the benefits of React's big community and facebook maintaining its vdom implementation.

**Comment by ghost** [comment]
Or if you want to continue the current effort. This might help as a premade vdom https://github.com/Matt-Esch/virtual-dom    Mercury and Elm are a couple view libs that use it which may help you hook it all up.

(I've been exploring all this stuff recently and thought this might be useful.)

**Comment by frozeman** [comment]
It would be great to have this a a separate package, which enhances blaze instead of messing with the core package.

**Comment by gadicc** [comment]
Hey all, sorry I never updated this.  The project has been discontinued.  I moved away from Blaze for the reasons mentioned [here](https://forums.meteor.com/t/is-blaze-still-worth-it-supported-in-the-future/11282/14?u=gadicc).

This mostly had to do with my impressions of MDG's intentions for Blaze, which proved correct (see some of the other posts in that thread).  As per the latest [official post](https://forums.meteor.com/t/next-steps-on-blaze-and-the-view-layer/13561), "Blaze 2" will be Spacebars-inspired templating built over React, so will benefit from React's vdom and I hope will ultimately reach the same performance as Blaze for [partial updates](https://forums.meteor.com/t/can-we-solve-react-cursor-inefficiency-vs-blaze/10590/).
